spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin